79 transition to real game
prijatelilab/PrijateliTree pull request #87
Opened 2023-12-01 22:44 UTC by FedericoDM

## Describe Your Changes

- 'Round' endpoint also leads to 'end of game' template

## Non-Obvious Technical Information

2023-12-01 22:46 UTC, FedericoDM commented
@anisfeld I fixed an issue where the 'round' endpoint didn't lead to the end of game. This was necessary for the 'session' loop that we will be having,

I am still a bit lost, however, on how to lead them from the practice game (or any game) to the following. 

Any thoughts?

2023-12-03 00:40 UTC, anisfeld commented
Good catch on stopping the loop! 

I'm not sure what particular part of this you are stuck on. 


# Testing for end of practice

All the integrated/segregated games are added to the database at session creation and the practice game(s) are noted as practice with a boolean in the database.

So the game table is heuristically looks like: 

| id | next_game_id| Practice | etc |
|--------|--------|--------|--------|
| 1 | 2| True | ... |
| 2 | 3 | True | ...|
| 3 | 4 | False | ... | 

So then, we need a test at the end of each game `is_end_of_practice()` that  checks if the current game is practice and if so, if the next game is *not* practice.  If so, we redirect the user to the welcome to the real game routes. 

# Game flow once test passes/fails

I think the place to put the test is in the `go_to_next_game` route. If is_end_of_practice() tell them that practice is over. 

I'm happy to discuss this further in real life.

2023-12-03 01:23 UTC, FedericoDM commented
@anisfeld Ok that makes it a bit clearer! Right now, when the game ends, we are redirecting game to the 'end of game' screen. Will this still be the case? I assume that, after this screen, we will see if the current game is just a practice game and if the next game is not.


We can meet in person next week to discuss this.

2023-12-04 05:32 UTC, FedericoDM commented
Transition screen looks like this:

![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/24a5ba61-0cfd-4b87-953a-dd33729f8ab5)

2023-12-04 05:32 UTC, FedericoDM commented
Transition into next game is successful, type of game is also displayed on the top right

![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/f2c410e2-2cc3-4272-8b8e-382e7f9b246c)

2023-12-04 05:40 UTC, FedericoDM commented
If the next game is not a practice game, it is redirected to the standard 'start_of_game' screen
![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/0a235f38-c77d-400b-aa05-95877cbe4c56)

2023-12-05 05:29 UTC, anisfeld commented
I think your solution for ending the game isn't working ... This is a practice game at round 9:
<img width="1273" alt="Screenshot 2023-12-04 at 11 28 41 PM" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/147f9d3e-a34c-4ee9-a280-660d8e5d69ef">

2023-12-05 07:04 UTC, FedericoDM commented
How many rounds does your game have? I had to reduce the number of rounds for practice and real games to 3 (it was set up to 10) @anisfeld

2023-12-06 00:56 UTC, anisfeld commented
Ah. I didn't think it would be 10 rounds--my bad! 

The end of round screen should be different for a practice game as well. It should not say they're getting paid.

2023-12-06 01:19 UTC, FedericoDM commented
Perfect @anisfeld! I'll make the changes for that and will let you know when they are done

2023-12-08 03:10 UTC, FedericoDM commented
Done, @anisfeld.

The end_of_game screen now displays the following text when the finished game was a practice one.

![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/5b7851e0-1646-4bc3-9c41-b1b3135a7450)

2023-12-08 05:27 UTC, anisfeld requested changes
This looks good. Just need to add the score (during real rounds)!

2023-12-08 05:27 UTC, anisfeld commented on prijateli_tree/app/routers/games.py
> +        redirect_url = f"/games/{game_id}/player/{player_id}/end_of_game"
The redirect should be to the function that adds the score.  As a complication, we don't want to add a score for practice games.

2023-12-08 17:24 UTC, FedericoDM commented
Added the redirect to the 'add points' @anisfeld

2023-12-09 07:13 UTC, anisfeld commented
The redirect didn't work.  Test the code by playing the game when you make changes. I use a mixture of my database viewer (DBeaver), browser, server log and command line to make sure things work the way I think they do. We will try to transition to more test-driven development moving forward. 

It seems like redirecting from GET to POST is taboo. I used the javascript code in waiting  + the all_set API to do the score updating. This might also be a bad idea in the long run since the logic of the game is now straddling python and javascript. 

In the meantime, I made too many changes! Please go through the code and act as a reviewer.

2023-12-09 23:06 UTC, FedericoDM commented
I have the same setup! I tested your changes and everything looks good, but I dont see any points being added to the db.

2023-12-12 03:13 UTC, FedericoDM commented
Should be ready to go! @anisfeld

2023-12-12 03:16 UTC, anisfeld approved these changes

2023-12-12 03:18 UTC, merged